### ISSUE TITLE
WASM compatible wallet

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/wallet.rs#1538]
- [x] Fix `unresolved import `tokio::sync::RwLock` (https://github.com/iotaledger/wallet.rs/pull/1539)
- [x] Fix `future cannot be sent between threads safely`
- [x] Write wasm bindings

**Comment by kwek20** [comment]
Q: What wasm target are we going for?
- [x] wasm32-unknown-unknown
- [ ] wasm32-unknown-emscripten
- [ ] wasm32-wasi

rocksdb: 
Missing headers for compiling to wasm, specifically threads
- [ ] https://github.com/rustwasm/team/issues/291#issuecomment-1343315089

Work on threads here: https://github.com/WebAssembly/threads

Stronghold:
- [ ] Missing `Frag` impl for wasm here:
  https://github.com/iotaledger/stronghold.rs/blob/dev/engine/runtime/src/memories/frag.rs
  https://docs.rs/wasmtime/latest/wasmtime/struct.Memory.html

Wallet.rs:
- [x] `tokio::spawn(async move )` wont work because !Send object in JsValue. Needs blocking API or mpsc(?)
  https://rustwasm.github.io/wasm-bindgen/api/src/wasm_bindgen/lib.rs.html#91
  -> Were going to use `spawn_local`

Ledger:
- [ ] [Hidapi ](https://github.com/ruabmbua/hidapi-rs) doesnt support wasm yet

Bindings:
- [ ] listen method
