### ISSUE TITLE
Fix address_conversion_methods test

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/wallet.rs#1610]
````
thread 'message_interface::tests::address_conversion_methods' panicked at 'assertion failed: `(left == right)`
  left: `"tst1qqk4svqpc89lxx89w7vksv9jgjjm2vwnrhad2j3cds9ev4cu434wjpfmeqx"`,
 right: `"rms1qqk4svqpc89lxx89w7vksv9jgjjm2vwnrhad2j3cds9ev4cu434wjapdsxs"`', src/message_interface/mod.rs:342:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test message_interface::tests::address_conversion_methods ... FAILED
```

**Comment by Thoralf-M** [comment]
rms is currently the default bech32 hrp, so when you run `cargo test` locally without having a node there, it fails. But in the CI we now run the private tangle, so it fails with this error, since the private tangle has tst as bech32 hrp
The options I see:
- use tst as default bech32 hrp in iota.rs (and update wallet.rs to that)
- use rms in the private tangle
- use a different node url in the test

**Comment by thibault-martinez** [comment]
Seems like I may have had a private tangle running which made the test fail 🤷🏻
