### ISSUE TITLE
[Bug]: Total balance incorrect if outputs with native token contain surplus SMR

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/wallet.rs#1809]
## Bug description

The available balance doesn't reflect the actual available balance. The problem probably arises when a user wants to spend an output with native tokens on, since those require extra storage deposit for the remainder output.

Example output which cannot be spent trivially: https://explorer.shimmer.network/testnet/output/0xcd605b063b3d470e3b92b2309c786f5ae1be14cf39b64e5f6d2d2e3ecc03399d0100

Original bug report: https://github.com/iotaledger/firefly/issues/5771

## Version

rc.19

- Version number, commit, or branch: 

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1. Have an output with native token
2. Try to increase voting power by available balance - storage deposit for basic outputs

## Expected behaviour

No error

## Actual behaviour

account.get_balance() returns the correct values, but it's impossible to send a transaction that spends those funds. 

## Errors

`insufficient amount: found error x, required y` error is thrown

**Comment by Thoralf-M** [comment]
I don't know what caused the difference in the Firefly issue, but the difference there is `399343200-378892800 = 20450400` which is not the amount of the output with the expiration (also couldn't find another output with such an amount for this address)
Still tried to reproduce and added a test which spends an expired output (linked PR) and it works fine, so the thing explained in this issue here is not true
Please open a new issue with a wallet log if you find another reason for the issue in Firefly

**Comment by Tuditi** [comment]
The difference arises due to the fact that I made multiple L2 transactions with an expiration unlock conditions. I'm going to reopen this issue with the wallet.log and send you the stronghold file, since the issue persists.

Here is the log file: 
[incorrect-balance.log](https://github.com/iotaledger/wallet.rs/files/10721839/incorrect-balance.log)

**Comment by thibault-martinez** [comment]
@Tuditi Can you let us know if this has been fixed now please?

**Comment by Tuditi** [comment]
Yup, it has been fixed.
